services:
  oboxsteam.api:
    image: ${DOCKER_REGISTRY-}oboxsteamapi
    container_name: obox-backend
    build:
      context: .
      dockerfile: OboxSteam.API/Dockerfile
    restart: unless-stopped
    depends_on:
      oboxsteam.database:
        condition: service_healthy
      # redis:
      #   condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
      # - ConnectionStrings__Redis=oboxsteam-redis:6379,abortConnect=false
      - JWT__SecretKey=${JWT__SecretKey}
      - JWT__Issuer=${JWT__Issuer}
      - JWT__Audience=${JWT__Audience}
      - RESEND_APITOKEN=${RESEND_APITOKEN}
      - RESEND_FROM=${RESEND_FROM}
      - APP_BASE_URL=${APP_BASE_URL}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}

    ports:
      - "${API_PORT}:5000"
    networks:
      - oboxsteam-network

  oboxsteam.database:
    image: postgres:15
    container_name: oboxsteam-database
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - oboxsteam-network

  # redis:
  #   image: redis:7.2-alpine
  #   container_name: oboxsteam-redis
  #   restart: unless-stopped
  #   ports:
  #     - "6380:6379"
  #   command: >
  #     redis-server
  #     --maxmemory 512mb
  #     --maxmemory-policy allkeys-lru
  #   volumes:
  #     - redis-data:/data
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 5s
  #     timeout: 3s
  #     retries: 10
  #   networks:
  #     - oboxsteam-network

volumes:
  pgdata:
  # redis-data:

networks:
  oboxsteam-network:
    driver: bridge
