using OboxSteam.Application.Utils;
using OboxSteam.Domain.Enums;
using OboxSteam.Domain.Interfaces;

namespace OboxSteam.Application.Validation;

/// <summary>
/// Guards curriculum structure changes (module/course/activity/assignment CRUD).
/// A program's curriculum is locked while any of its classes is in progress, or while
/// any open class already has enrolled students — structural changes are meant to land
/// between cohorts: in-progress classes finish on the curriculum they started with,
/// and draft/open-but-empty classes are re-generated by the manager after the change.
/// </summary>
public static class CurriculumEditGuard
{
    public static async Task EnsureProgramCurriculumEditableAsync(IUnitOfWork unitOfWork, Guid programId)
    {
        var classes = await unitOfWork.Classes.GetAllAsync(
            c => c.ProgramId == programId
                 && !c.IsDeleted
                 && (c.Status == ClassStatus.InProgress || c.Status == ClassStatus.Open));

        if (classes.Any(c => c.Status == ClassStatus.InProgress))
        {
            throw ErrorHelper.Conflict(
                "Program curriculum cannot be changed while a class is in progress. " +
                "Wait for in-progress classes to complete — curriculum changes apply to new cohorts.");
        }

        var openClassIds = classes
            .Where(c => c.Status == ClassStatus.Open)
            .Select(c => c.Id)
            .ToList();

        if (openClassIds.Count == 0)
        {
            return;
        }

        var hasEnrolledStudents = unitOfWork.ClassEnrollments
            .GetQueryable()
            .Any(e => openClassIds.Contains(e.ClassId)
                      && e.Status == ClassEnrollmentStatus.Active
                      && !e.IsDeleted);

        if (hasEnrolledStudents)
        {
            throw ErrorHelper.Conflict(
                "Program curriculum cannot be changed while an open class has enrolled students.");
        }
    }
}
